services:
  web:
    image: mpdn-fpm
    # build:
    #   context: .
    #   dockerfile: ./alpine-fpm/Dockerfile
    container_name: web
    platform: linux/amd64
    environment:
      - FPM_PM=dynamic
      - FPM_PM_MAX_CHILDREN=5
      - FPM_PM_START_SERVERS=2
      - FPM_PM_MIN_SPARE_SERVERS=1
      - FPM_PM_MAX_SPARE_SERVERS=3
      - FPM_SESSION_SAVE_PATH=memcache:11211
      - PHP_UPLOAD_MAX_FILESIZE=8M
      - PHP_POST_MAX_SIZE=8M
      - REPOSND=timkubus:glpat-Wekw2btFSN3GdfbTu216
      - TIMEZONE=Asia/Jakarta
      - DOMAIN=mpdn.kemkes.go.id
      - REPO_BASE=https://gitlab.com/webcore2/main-prod.git
      - CONFIG_BASE=https://gitlab.com/docker-setup/config-mpdn-kemkes.git
    ports:
      - "80:80"
    networks:
      - webcore-net
    volumes:
      - ./mount/web:/app/mpdn
    depends_on:
      - memcache
      - database
  
  memcache:
    image: memcached:latest
    container_name: memcached
    ports:
     - "11211:11211"
    networks:
     - webcore-net

  database:
    image: mariadb:10.4
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webcore
      MYSQL_USER: webcore
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - webcore-net
    volumes:
      - ./mount/data:/var/lib/mysql

networks:
  webcore-net:
    driver: bridge
