services:
  backend:
    image: mpdn:fpm-latest
    container_name: backend
    environment:
      - PHP_VERSION=7.4.28
      - FPM_PM=dynamic
      - FPM_PM_MAX_CHILDREN=5
      - FPM_PM_START_SERVERS=2
      - FPM_PM_MIN_SPARE_SERVERS=1
      - FPM_PM_MAX_SPARE_SERVERS=3
      - FPM_SESSION_SAVE_PATH=memcache:11211
      - PHP_UPLOAD_MAX_FILESIZE=8M
      - PHP_POST_MAX_SIZE=8M
      - APPDIR=/app
      - PROJECT=mpdn
      - REPOSND=timkubus:glpat-Wekw2btFSN3GdfbTu216
      - TIMEZONE=Asia/Jakarta
      - DOMAIN=mpdn.kemkes.go.id
    ports:
      - "9000:9000"
    # volumes:
    #   - ./app:/var/www/html
    networks:
      - webcore-net
    # depends_on:
    #   - mysql
  
  frontend:
    image: nginx
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      # - ./app:/var/www/html:ro
      - ./supporting_files/nginx_default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - webcore-net

  
  memcache:
    image: memcached:latest
    container_name: memcached
    ports:
     - "11211:11211"
    networks:
     - webcore-net

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: webcore
  #     MYSQL_USER: webcore
  #     MYSQL_PASSWORD: webcorepassword
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - webcore-net
  #   volumes:
  #     - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data:

networks:
  webcore-net:
    driver: bridge
